### PR TITLE
Added GameMode, EntityType and World arguments

### PR DESCRIPTION
**Pull request by cerus**
# Pull Request Template

## Checklist

* [X] There is an existing issue report for this PR. If not so, create one first.
* [X] I have forked this project.
* [X] I have created a feature branch.
* [X] My changes have been committed.
* [X] I have pushed my changes to the branch.
* [X] Running `mvn checkstyle:check` doesn't fail.

## Title
Added more Spigot arguments

## Description
I added arguments for GameMode, EntityType and World. 

## Issue Resolution

This Pull Request addresses #28 

## Proposed Changes
* Added GameMode argument
* Added EntityType argument
* Added World argument

### CODE REVIEW

**Comment by Paul2708** [comment]
First of all, thanks for your contribution!
I also appreciate that you used to give code style.

Before merging in `development`, I would address some changes caused by my poor documentation. 😢 

`enum` argument commands like `EntityTypeArgument` are already covered by `EnumArgument`.
So could you remove it and its resource messages?
And could you register the other arguments in `ArgumentHolder`?

Would be great.
Sorry for these circumstances.

**Comment by cerus** [comment]
Hey,
no problem, I'll remove the conflicts asap!

**Comment by Paul2708** [comment]
Thanks for your contribution!

**Comment by cerus** [comment]
No problem. :)

**Pull request merged**
